### PR TITLE
Fixes Issue #1: Re-enables JS linting

### LINKED ISSUE #1: Turn JSHint back on for src files
Currently turned off due to `/* jshint ignore:start */` not working in the latest available JSHint release (jshint/jshint#2411).

We're using `ignore` because we're more-or-less directly pasting in the Zendesk widget embed code. Otherwise, we'd have to format their minified JS.

### PR DESCRIPTION
**Pull request by kanhirun**
# Summary
1. Fixes #1 
2. Replaces JSHint with [ESLint](http://eslint.org/) to use the same tool as crosslead-platform

(I suggest that we extract the linting configuration to make it available organization-wide. You can use [git submodules](https://git-scm.com/docs/git-submodule) for this. This way, there won't be duplication of knowledge, and avoids the adhocity trap.)

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -62,12 +62,23 @@ gulp.task('watch', function () {
 /**
  * Validate source JavaScript
  */
-gulp.task('jshint', function () {
+gulp.task('lint', function () {
```
Comment (kanhirun) [inline gulpfile.js:65]: When linting, the user shouldn't know what linter they are using. Instead, they should just invoke the command, and resolve conflicts.

File: gulpfile.js [hunk 2]
```diff
@@ -62,12 +62,23 @@ gulp.task('watch', function () {
...
   return gulp.src(lintFiles)
     .pipe(plumber())
-    .pipe(jshint())
-    .pipe(jshint.reporter('jshint-stylish'))
-    .pipe(jshint.reporter('fail'));
+    .pipe(eslint({
+      extends: 'eslint:recommended',
```
Comment (kanhirun) [inline gulpfile.js:69]: I just inlined the configuration options here, but I saw that crosslead-platform has a `.eslintrc` file. I suggest—in the PR—a way to avoid falling into this adhocity trap.

Comment (bsouthga) [inline gulpfile.js:69]: Good idea, that we can spread our linting gospel to the masses.

**Comment by bsouthga** [comment]
Looks good to me!
